name: Check Terraform

on:
  push:
    branches: ['*', '!master']

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  check-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - uses: dwd/secrets-vault@master
        with:
          vault_key: ${{ secrets.VAULT_KEY }}
          environment: ci
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format Check
        run: terraform fmt -check
      - name: Gather deployment files
        run: echo main_files = '[]' > ../terraform/vars.tfvars
      - name: Gather deployment files
        run: echo sb_files = '[]' >> ../terraform/vars.tfvars
        working-directory: storybook-static/
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan -no-color
