name: Check Terraform

on:
  push:
    branches: ['*', '!master']

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  check-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - uses: dwd/secrets-vault@master
        with:
          vault_key: ${{ secrets.VAULT_KEY }}
          environment: ci
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./terraform
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform
      - name: Terraform Plan
        run: terraform plan -no-color -var sb_files='[]' -var main_files='[]'
        working-directory: ./terraform
