name: Check Secrets

on:
  push:
    branches: ['*', '!master']

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dwd/secrets-vault@master
        with:
          vault_key: ${{ secrets.VAULT_KEY }}
          mode: lint
